const suggestionsHouse = [
    { label: 'CENTRO' },
    { label: 'ZONA RURAL' },
    { label: 'BAIRRO - BELA VISTA' },
    { label: 'BAIRRO - CASTELO BRANCO' },
    { label: 'BAIRRO - SAO SEBASTIAO' },
    { label: 'BAIRRO - SANTO AMARO' },
    { label: 'BAIRRO - JOSÉ PESSOA DE BRITO' },
    { label: 'BAIRRO - EMÍLIA BORGES ' },
    { label: 'SÍTIO - BONITA' },
    { label: 'SÍTIO - BARRA DA ESPINGARDA' },
    { label: 'SÍTIO - CANAFISTULA' },
    { label: 'SÍTIO - CANAFISTINHA' },
    { label: 'SÍTIO - CACHOEIRA' },
    { label: 'SÍTIO - CIPOAL' },
    { label: 'SÍTIO - CHA DO MASCATE' },
    { label: 'SÍTIO - CUITE MENINO DEUS' },
    { label: 'SÍTIO - JACINTO' },
    { label: 'SÍTIO - LAGOA DAS VELHAS' },
    { label: 'SÍTIO - LAGOA DO FELIX' },
    { label: 'SÍTIO - MATA DE ESTREITO' },
    { label: 'SÍTIO - MASCATE' },
    { label: 'SÍTIO - MARMARAU' },
    { label: 'SÍTIO - MEREREBA' },
    { label: 'SÍTIO - MERCADOR DE BAIXO' },
    { label: 'SÍTIO - MERCADOR DE CIMA' },
    { label: 'SÍTIO - MUNLUNGUZINHO' },
    { label: 'SÍTIO - OLHO D`ÀGUA' },
    { label: 'SÍTIO - Tainha' },
    { label: 'SÍTIO - GENIPAPO DE TAUMATA' },
    { label: 'SÍTIO - GRAVATA DE PIABAS' },
    { label: 'SÍTIO - GUARIBAS' },
    { label: 'SÍTIO - PACHECO ' },
    { label: 'SÍTIO - PITOMBAS' },
    { label: 'SÍTIO - PIABAS' },
    { label: 'SÍTIO - RIACHO GRNADE' },
    { label: 'SÍTIO - RIACHO DE BAIXO' },
    { label: 'SÍTIO - SANTA LUCIA' },
    { label: 'SÍTIO - SAO VICENTE' },
    { label: 'SÍTIO - VIOLETA' },
];

export default suggestionsHouse;